<?php

/**
 * @file
 * Primary module hooks for Neo | Modal module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\neo_icon\IconElement;
use Drupal\neo_modal\Modal;

/**
 * Implements hook_theme().
 */
function neo_modal_theme(): array {
  return [
    'neo_modal' => [
      'render element' => 'element',
    ],
    'neo_modal_trigger_overlay' => [
      'variables' => [
        'title' => '',
        'icon' => '',
        'attributes' => [],
      ],
    ],
    'neo_modal_account' => [
      'variables' => [
        'title' => '',
        'message' => '',
        'menu_account' => [],
        'menu_tools' => [],
        'register_title' => '',
        'register' => [],
        'user' => [],
        'form' => [],
        'primary_link' => [],
        'secondary_link' => [],
        'logout_link' => [],
      ],
    ],
  ];
}

/**
 * Implements template_preprocess().
 */
function template_preprocess_neo_modal(&$variables) {
  $variables['has_parent'] = FALSE;
  $element = $variables['element'];
  // Ensure #attributes is set.
  $element += ['#attributes' => []];

  // Special handling for form elements.
  if (isset($element['#array_parents'])) {
    // Assign an html ID.
    if (!isset($element['#attributes']['id'])) {
      $element['#attributes']['id'] = $element['#id'];
    }
    $variables['has_parent'] = TRUE;
  }

  $variables['children'] = $element['#children'];
  $variables['attributes'] = $element['#attributes'];
}

/**
 * Implements hook_module_implements_alter().
 */
function neo_modal_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'library_info_alter') {
    // Move my_module_form_alter() to the end of the list.
    $group = $implementations['neo_modal'];
    unset($implementations['neo_modal']);
    $implementations['neo_modal'] = $group;
  }
}

/**
 * Implements hook_library_info_alter().
 */
function neo_modal_library_info_alter(&$libraries, $extension) {
  if ($extension == 'core') {
    $path = '/' . \Drupal::service('extension.list.module')->getPath('neo');

    $libraries['drupal.dialog']['css'] = [];
    $libraries['drupal.dialog']['js'] = [];

    // A library with no js or css will not be added to the page when
    // aggregation is enabled. So we add a js file that does nothing.
    $libraries['drupal.dialog']['js'][$path . '/js/na.js'] = ['minified' => TRUE];
    $libraries['drupal.dialog']['dependencies'][] = 'neo_modal/modal';

    $libraries['drupal.dialog.ajax']['js'] = [];
    // A library with no js or css will not be added to the page when
    // aggregation is enabled. So we add a js file that does nothing.
    $libraries['drupal.dialog.ajax']['js'][$path . '/js/na.js'] = ['minified' => TRUE];
    $libraries['drupal.dialog.ajax']['dependencies'][] = 'neo_modal/modal-dialog-ajax';
    $libraries['drupal.dialog.ajax']['dependencies'] = array_values(array_filter($libraries['drupal.dialog.ajax']['dependencies'], function ($value) {
      return $value !== 'core/jquery';
    }));
  }
  if ($extension == 'focal_point') {
    // Focal point relies on core.dialog loading JQuery UI. But since we replace
    // it, we need to add the libraries it needs.
    $libraries['drupal.focal_point']['js']['/core/assets/vendor/jquery.ui/ui/widgets/draggable-min.js'] = [
      'weight' => '-11.6',
      'minified' => TRUE,
    ];
    $libraries['drupal.focal_point']['js']['/core/assets/vendor/jquery.ui/ui/widgets/mouse-min.js'] = [
      'weight' => '-11.7',
      'minified' => TRUE,
    ];
    $libraries['drupal.dialog.ajax']['dependencies'][] = 'core/internal.jquery_ui';
  }
}

/**
 * Implements hook_ajax_render_alter().
 */
function neo_modal_ajax_render_alter(array &$data) {
  foreach ($data as $delta => $command) {
    if ($command['command'] == 'ajaxRedirect') {
      if (!empty($command['data']['dialog']['neo'])) {
        $modal = new Modal(NULL, $command['data']['dialog']['neo'], $command['data']['dialog']['neo']['preset'] ?? 'dialog');
        $data[$delta]['data']['dialog']['neo'] = $modal->getValues();
      }
    }
    if ($command['command'] == 'openDialog') {
      if (!empty($command['dialogOptions'])) {
        $data[$delta]['settings'] = $data[$delta]['settings'] ?? [];
        if (!empty($command['dialogOptions']['title'])) {
          $data[$delta]['settings']['title'] = $command['dialogOptions']['title'];
          if (empty($command['dialogOptions']['neo']['icon'])) {
            $iconElement = new IconElement($command['dialogOptions']['title'], NULL, NULL, ['any']);
            if ($icon = $iconElement->getIcon()) {
              $data[$delta]['settings']['icon'] = $icon->getSelector();
            }
          }
        }
        if (!empty($command['dialogOptions']['width']) && $command['dialogOptions']['width'] != 'auto') {
          $data[$delta]['settings']['width'] = $command['dialogOptions']['width'];
        }
        if (!empty($command['dialogOptions']['height']) && $command['dialogOptions']['height'] != 'auto') {
          $data[$delta]['settings']['height'] = $command['dialogOptions']['height'];
        }
        if (!empty($command['dialogOptions']['position']['my'])) {
          $data[$delta]['settings']['placement'] = str_replace(' ', '-', str_replace('top', 'start', str_replace('bottom', 'end', $command['dialogOptions']['position']['my'])));
        }
        if (!empty($command['dialogOptions']['classes'])) {
          if (in_array('media-library-widget-modal', $command['dialogOptions']['classes'])) {
            $data[$delta]['settings']['width'] = '100%';
            $data[$delta]['settings']['height'] = '100%';
            $data[$delta]['settings']['nest'] = TRUE;
          }
          if (in_array('views-ui-dialog js-views-ui-dialog', $command['dialogOptions']['classes'])) {
            $data[$delta]['settings']['width'] = '100%';
            $data[$delta]['settings']['height'] = '100%';
            $data[$delta]['settings']['nest'] = FALSE;
          }
          $data[$delta]['settings']['modalClasses'] = implode(' ', $command['dialogOptions']['classes']);
        }
        if (!empty($command['dialogOptions']['neo'])) {
          $data[$delta]['settings'] += $command['dialogOptions']['neo'];
          unset($data[$delta]['settings']['neo']);
        }

        $modal = new Modal(NULL, $data[$delta]['settings'], $data[$delta]['settings']['preset'] ?? 'dialog');
        $data[$delta]['settings'] = $modal->getValues() + $data[$delta]['settings'];
      }
    }
  }
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function neo_modal_menu_local_actions_alter(&$local_actions) {
  foreach ($local_actions as $id => $action) {
    if (isset($action['modal'])) {
      $local_actions[$id]['modal'] = is_array($local_actions[$id]['modal']) ? $local_actions[$id]['modal'] : [];
      $local_actions[$id]['class'] = '\Drupal\neo_modal\Plugin\Menu\LocalAction\ModalLocalAction';
    }
  }
}

/**
 * Implements hook_element_info_alter().
 */
function neo_modal_element_info_alter(array &$info) {
  $info['submit']['#process'][] = 'neo_modal_submit_process';
}

function neo_modal_submit_process(&$element, FormStateInterface $form_state, $form) {
  if (!empty($element['#modal_close'])) {
    $element['#attributes']['data-neo-modal-close-submit'] = TRUE;
  }
  return $element;
}
